// Package doc Code generated by swaggo/swag. DO NOT EDIT
package doc

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/good/{id}": {
            "get": {
                "description": "Get Goods By ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Goods"
                ],
                "summary": "Get Good By ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Good ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GetGoodByIDResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.GoodNotFoundResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.InternalResponse"
                        }
                    }
                }
            }
        },
        "/goods": {
            "get": {
                "description": "Get Goods List",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Goods"
                ],
                "summary": "Get Goods",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GetGoodsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.InternalResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.GetGoodByIDResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/model.Good"
                },
                "msg_code": {
                    "type": "string",
                    "example": "good_received"
                },
                "status": {
                    "type": "string",
                    "example": "OK"
                }
            }
        },
        "model.GetGoodsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Good"
                    }
                },
                "msg_code": {
                    "type": "string",
                    "example": "goods_received"
                },
                "status": {
                    "type": "string",
                    "example": "OK"
                }
            }
        },
        "model.Good": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-03-24T21:16:31Z"
                },
                "deleted_at": {
                    "type": "string",
                    "example": "null"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "T-Shirt"
                },
                "size": {
                    "type": "string",
                    "example": "s"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-03-24T21:16:31Z"
                }
            }
        },
        "model.GoodNotFoundResponse": {
            "type": "object",
            "properties": {
                "msg_code": {
                    "type": "string",
                    "example": "good_not_found"
                },
                "status": {
                    "type": "string",
                    "example": "ERROR"
                }
            }
        },
        "model.InternalResponse": {
            "type": "object",
            "properties": {
                "msg_code": {
                    "type": "string",
                    "example": "general_internal"
                },
                "status": {
                    "type": "string",
                    "example": "ERROR"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "server:8080",
	BasePath:         "/hub/api/v1",
	Schemes:          []string{},
	Title:            "Lamoda Intentory Hub API",
	Description:      "Lamoda Intentory Hub API Service Documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
